# This file ingests the STL file from pyCoilGen that works well only with a sweep
"""
Module: write_stl_without_sweep.py
This module processes STL files generated by pyCoilGen to remove sweep effects from wire paths
and extract centerline coordinates for 3D printing and wire bending applications.
Dependencies:
    - trimesh: For loading and manipulating STL mesh files
    - numpy: For numerical array operations
    - pandas: For data manipulation and Excel file operations
    - scipy: For spatial operations and cubic spline interpolation
    - scikit-learn: For clustering algorithms (DBSCAN)
    - matplotlib: For 3D visualization of wire paths
Required Import for CubicSpline:
Main Workflow:
    1. Load STL file and visualize wire paths with sweep effect
    2. Calculate moving average of x,y coordinates to smooth vertices
    3. Identify deviated coordinates from initial y-plane
    4. Segment curves based on index gaps
    5. Generate smooth spline curves between curve endpoints
    6. Remove duplicate or too-close adjacent vertices
    7. Extract wire path centerline coordinates
    8. Export coordinates to text file for CAD software import
Output:
    - Visualization plots of original, adjusted, and smoothed wire paths
    - Text file containing wire path coordinates (x, y, z per line)
"""
# and the xyz coordinates of the centers of the wire paths to an excel file.
# Step 1: Load the STL file and visualize the wire paths with sweep
# Step 2: Find the moving average of the x,y coordinates for every 10 vertices
# Step 3: Save the modified mesh to a new STL file  
# Step 4: Extract wire path coordinates and save to Excel

import trimesh
import numpy as np
import pandas as pd
import os
import logging
logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 
from scipy.spatial import cKDTree
from sklearn.cluster import DBSCAN
from scipy.spatial.distance import cdist
from scipy.interpolate import CubicSpline

# Step 1: Load the STL file and visualize the wire paths 
stl_file_path = "./images/Tenacity_gradient_print_z_wire_1_z.stl"
txt_output_path = stl_file_path.replace('.stl', '.txt')
mesh = trimesh.load_mesh(stl_file_path)
log.info(f"Loaded mesh with {len(mesh.vertices)} vertices and {len(mesh.faces)} faces.")


# Now lets visualize the mesh to see the wire paths with sweep from the vertices and faces
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(mesh.vertices[:, 0], mesh.vertices[:, 1], mesh.vertices[:, 2], 'b.')
ax.set_title('With Sweep Wire Paths')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.show()


# Step 2: Find the moving average of the x,y coordinates for every 10 vertices along z to remove the sweep effect
# Calculate the moving average of x, y coordinates for every 10 vertices along z
window_size = 50
x_coords = mesh.vertices[:, 0]
y_coords = mesh.vertices[:, 1]
z_coords = mesh.vertices[:, 2]
initial_y_plane = np.mean(y_coords[:5])
vertices_adjusted = mesh.vertices.copy()

# Create an array to hold the adjusted coordinates
adjusted_coords = vertices_adjusted.copy()
for i in range(len(mesh.vertices)):
    start_idx = max(0, i - window_size // 2)
    end_idx = min(len(mesh.vertices), i + window_size // 2 + 1)
    window = mesh.vertices[start_idx:end_idx, :]
    adjusted_coords[i, :] = np.mean(window[:, 0])
    adjusted_coords[i, 1] = np.mean(window[:, 1])
    adjusted_coords[i, 2] = np.mean(window[:, 2])
   
        
# The vertices are stacked according to z-levels now but we need them to be back in original like wire paths
vertices_adjusted = adjusted_coords

# Update mesh with adjusted vertices before checking and exporting
mesh.vertices = vertices_adjusted


fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(vertices_adjusted[:, 0], vertices_adjusted[:, 1], vertices_adjusted[:, 2], 'b-')
ax.set_title('Adjusted Vertices without Sweep')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.show()


# Identify and plot coordinates in vertices_adjusted that are more than abs(1.75) away from the initial y plane
deviated_coords = vertices_adjusted[np.abs(vertices_adjusted[:, 1] - initial_y_plane) > 0.01]
# Store the corresponding indices of the deviated coordinates
deviated_indices = np.where(np.abs(vertices_adjusted[:, 1] - initial_y_plane) > 0.01)[0]  
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(deviated_coords[:, 0], deviated_coords[:, 1], deviated_coords[:, 2], 'ro-')
ax.set_title('Deviated Coordinates from Initial Y Plane')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.show()


# Identify the curves in the deviated coordinates if there is a significant gap between the indices in adjusted vertices, it probably indicates a new curve
# Find gaps in deviated indices to identify separate curves
gaps = np.where(np.diff(deviated_indices) > 1)[0]
curve_starts = np.insert(gaps + 1, 0, 0)  # Start of each curve
curve_ends = np.append(gaps, len(deviated_indices) - 1)  # End of each curve

# Log the identified curves
for ind_curve in range(len(curve_starts)):
    log.info(f"Identified curve from index {deviated_indices[curve_starts[ind_curve]]} to {deviated_indices[curve_ends[ind_curve]]}")


# Change the depth of the three curves to be at different y-plane values to help 3D printing and wire bending
# First smooth the three curves to remove sharp turns in y-axis
normal_shift_length = 2
curves = []
sign_use = -1

# Plot the smoothed curves
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
for ind_curve in range(len(curve_starts)):
    curve_indices = deviated_indices[curve_starts[ind_curve]:curve_ends[ind_curve]+1]
    curve_coords = vertices_adjusted[curve_indices, :]
    curves.append(curve_coords)
    
    curve_start = curve_coords[0, :]
    curve_end = curve_coords[-1, :]
    curve_deepest_y = initial_y_plane  + ((normal_shift_length * (ind_curve + 1)) * sign_use)   # Shift each curve deeper by 0.5m increments
    sign_use *= -1  # Alternate the sign for next curve

    # Generate a smooth spline connecting curve_start and curve_end with a midpoint at curve_deepest_y
    t = np.linspace(0, 1, len(curve_coords))
    midpoint = np.array([(curve_start[0] + curve_end[0]) / 2, curve_deepest_y, (curve_start[2] + curve_end[2]) / 2])
    spline_points = np.array([curve_start, midpoint, curve_end])

    # Create a cubic spline interpolation
    cs = CubicSpline([0, 0.5, 1], spline_points, axis=0)
    smooth_curve = cs(t)
    
    # # Ensure the current curve is at least distance 2 away from previous curves
    # if ind_curve > 0:
    #     for prev_curve in curves[:-1]:
    #         min_dist_to_prev = np.min(cdist(smooth_curve, prev_curve))
    #         if min_dist_to_prev < 2:
    #             # Adjust curve_deepest_y to increase separation
    #             adjustment = 2 - min_dist_to_prev + 0.5
    #             curve_deepest_y += adjustment
    #             midpoint = np.array([(curve_start[0] + curve_end[0]) / 2, curve_deepest_y, (curve_start[2] + curve_end[2]) / 2])
    #             spline_points = np.array([curve_start, midpoint, curve_end])
    #             cs = CubicSpline([0, 0.5, 1], spline_points, axis=0)
    #             smooth_curve = cs(t)

    # Replace the original curve coordinates with the smooth curve
    vertices_adjusted[curve_indices, :] = smooth_curve
    ax.plot(smooth_curve[:, 0], smooth_curve[:, 1], smooth_curve[:, 2], color=plt.cm.tab10(ind_curve))

   

# Sharp turns between curves cause sweep to fail in solidworks - need to smooth those too
# Make sure there are no steep turns > 45 degrees in the x-z plane between adjacent points 
angle_store = np.zeros(len(vertices_adjusted))
for i in range(1, len(vertices_adjusted)-1):
    vec1 = vertices_adjusted[i] - vertices_adjusted[i-1]
    vec2 = vertices_adjusted[i+1] - vertices_adjusted[i]
    cos_angle = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
    angle_store[i] = np.rad2deg(np.arccos(np.clip(cos_angle, -1.0, 1.0)))  # Angle in radians
    
# Plot a 3D figure of the angles at each point to visualize
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
scatter = ax.scatter(vertices_adjusted[:, 0], vertices_adjusted[:, 1], vertices_adjusted[:, 2], c=angle_store, cmap='viridis', s=10)
ax.set_title('Angles at Each Vertex')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
cbar = plt.colorbar(scatter, ax=ax, label='Angle (degrees)')
plt.show()


# Remove the sharp turns by fitting a cubic spline to those segments
sharp_turn_indices = np.where(angle_store > 30)[0]
for idx in sharp_turn_indices:
    if idx > 1 and idx < len(vertices_adjusted) - 2:
        segment_indices = np.arange(idx - 2, idx + 3)
        segment_coords = vertices_adjusted[segment_indices, :]
        t_segment = np.linspace(0, 1, len(segment_coords))
        cs_segment = CubicSpline(t_segment, segment_coords, axis=0)
        t_fine = np.linspace(0, 1, 50)
        smooth_segment = cs_segment(t_fine)
        # Replace the original segment with the smooth segment (interpolated back to original indices)
        for j, seg_idx in enumerate(segment_indices):
            vertices_adjusted[seg_idx, :] = smooth_segment[int(j * (len(t_fine) - 1) / (len(segment_indices) - 1)), :]

# Make sure the vertices are all 2 decimal places before writing to the text file
vertices_adjusted = np.round(vertices_adjusted, 2)

# Step 4: Remove duplicate or too-close adjacent vertices
min_distance = 2 # Minimum distance threshold
filtered_vertices = [vertices_adjusted[0]]

for i in range(1, len(vertices_adjusted)):
    distance = np.linalg.norm(vertices_adjusted[i] - filtered_vertices[-1])
    if distance > min_distance:
        filtered_vertices.append(vertices_adjusted[i])

vertices_adjusted = np.array(filtered_vertices)
log.info(f"Removed {len(filtered_vertices) - len(vertices_adjusted)} duplicate or too-close vertices")



print(f"Number of vertices after interpolation: {len(vertices_adjusted)}")
# Interpolate to get new vertices
# Visualize the smoothed wire path
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(vertices_adjusted[:, 0], vertices_adjusted[:, 1], vertices_adjusted[:, 2], 'r-')
ax.set_title('Final Smoothed Wire Path without Sweep')
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.show()




# Extract wire path centerline coordinates
wire_path = np.array([[np.round(vertices_adjusted[i, 0], 2), np.round(vertices_adjusted[i, 1], 2), np.round(vertices_adjusted[i, 2], 2)] 
                       for i in range(len(vertices_adjusted)-5)]) # will skip the last vertex to enable operations in solidworks


# Also write a simple text file for direct import to solidworks with no heading but only coordinates - one coordianate per line and x, y and z separated by space

with open(txt_output_path, 'w') as f:
    for point in wire_path:
        f.write(f"{point[0]} {point[1]} {point[2]}\n")
log.info(f"Saved wire path coordinates to {txt_output_path}")






